### Register new user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "User 1",
  "email": "user1@email.com",
  "password": "secret"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "user1@email.com",
  "password": "secret"
}